sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mryesiller/react-todoapp -f Dockerfile.dev .
  - gem install faraday -v 1.8.0

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_ACCESS_KEY
  app: mryesiller-react-todoapp
  on:
    repo: mryesiller/react-todoapp
