sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f mryesiller/react-todoApp Dockerfile.dev .

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_ACCESS_KEY
