sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -f mryesiller/react-todoApp Dockerfile.dev .

script:
  - docker run -e CI=true mryesiller/react-todoApp npm run test
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_ACCESS_KEY
