sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mryesiller/react-todoapp -f Dockerfile.dev .
  - rvm install 2.2.5

deploy:
  provider: heroku
  api_key: $HEROKU_ACCESS_KEY
